# Generated by Django 4.2.15 on 2024-08-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['first_name', 'last_name'], name='employees_e_first_n_597cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['contact_email'], name='employees_e_contact_2271ff_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='employees_e_positio_bc0128_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['location'], name='employees_e_locatio_97f783_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employees_e_status_61c2f6_idx'),
        ),
    ]
